package com.jiayuewen.bean;

import java.util.Date;

public class Appointment extends AppointmentKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.appoint_time
     *
     * @mbg.generated Tue Aug 20 21:59:41 CST 2019
     */
    private Date appointTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.appoint_time
     *
     * @return the value of appointment.appoint_time
     *
     * @mbg.generated Tue Aug 20 21:59:41 CST 2019
     */
    public Date getAppointTime() {
        return appointTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.appoint_time
     *
     * @param appointTime the value for appointment.appoint_time
     *
     * @mbg.generated Tue Aug 20 21:59:41 CST 2019
     */
    public void setAppointTime(Date appointTime) {
        this.appointTime = appointTime;
    }
}