package com.jiayuewen.mapper;

import com.jiayuewen.bean.Appointment;
import com.jiayuewen.bean.AppointmentExample;
import com.jiayuewen.bean.AppointmentKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppointmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbg.generated Tue Aug 20 21:59:41 CST 2019
     */
    long countByExample(AppointmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbg.generated Tue Aug 20 21:59:41 CST 2019
     */
    int deleteByExample(AppointmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbg.generated Tue Aug 20 21:59:41 CST 2019
     */
    int deleteByPrimaryKey(AppointmentKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbg.generated Tue Aug 20 21:59:41 CST 2019
     */
    int insert(Appointment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbg.generated Tue Aug 20 21:59:41 CST 2019
     */
    int insertSelective(Appointment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbg.generated Tue Aug 20 21:59:41 CST 2019
     */
    List<Appointment> selectByExample(AppointmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbg.generated Tue Aug 20 21:59:41 CST 2019
     */
    Appointment selectByPrimaryKey(AppointmentKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbg.generated Tue Aug 20 21:59:41 CST 2019
     */
    int updateByExampleSelective(@Param("record") Appointment record, @Param("example") AppointmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbg.generated Tue Aug 20 21:59:41 CST 2019
     */
    int updateByExample(@Param("record") Appointment record, @Param("example") AppointmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbg.generated Tue Aug 20 21:59:41 CST 2019
     */
    int updateByPrimaryKeySelective(Appointment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbg.generated Tue Aug 20 21:59:41 CST 2019
     */
    int updateByPrimaryKey(Appointment record);
    
    //以下为手动添加
    /**
     * 获取某位学生的所有预约记录
     * @param studentId
     * @return
     */
    List<Appointment> getAppointByStudentId(long studentId);
    
    /**
     * 生成一条预约记录
     * @param bookId	传递多个参数用@Param标注
     * @param studentId
     */
    void appoint(@Param("bookId")long bookId, @Param("studentId")long studentId);
    
    /**
     * 删除一条预约记录
     * @param bookId	传递多个参数用@Param标注
     * @param studentId
     */
    void deleteAppoint(@Param("bookId")long bookId, @Param("studentId")long studentId);
}