package com.jiayuewen.mapper;

import com.jiayuewen.bean.Book;
import com.jiayuewen.bean.BookExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Tue Aug 20 21:59:41 CST 2019
     */
    long countByExample(BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Tue Aug 20 21:59:41 CST 2019
     */
    int deleteByExample(BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Tue Aug 20 21:59:41 CST 2019
     */
    int deleteByPrimaryKey(Long bookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Tue Aug 20 21:59:41 CST 2019
     */
    int insert(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Tue Aug 20 21:59:41 CST 2019
     */
    int insertSelective(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Tue Aug 20 21:59:41 CST 2019
     */
    List<Book> selectByExample(BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Tue Aug 20 21:59:41 CST 2019
     */
    int updateByExampleSelective(@Param("record") Book record, @Param("example") BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Tue Aug 20 21:59:41 CST 2019
     */
    int updateByExample(@Param("record") Book record, @Param("example") BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Tue Aug 20 21:59:41 CST 2019
     */
    int updateByPrimaryKeySelective(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Tue Aug 20 21:59:41 CST 2019
     */
    int updateByPrimaryKey(Book record);
    
    //以下为手动添加
    /**
     * 获取所有图书
     * @return
     */
    List<Book> getAllBook();
    
    /**
     * 通过书名查找图书
     * @return
     */
    List<Book> getBookByName(String name);
    
    /**
     * 统计某种书的数量
     * @param bookId
     * @return
     */
    int getBookCountByBookId(long bookId);    
    
    /**
     * 通过bookId查找图书
     * @param bookId
     * @return
     */
    Book selectByPrimaryKey(Long bookId);
    
    /**
     * 被预约书的可预约数量减一
     * @param bookId
     */
    void updateAppointNo(Long bookId);
    
    /**
     * 被取消的预约的书的可预约数量加一
     * @param bookId
     */
    void updateAddAppointNo(Long bookId);
}














